version: 1
base_currency: TWD

fx_rates:
  USD: 32.0
  TWD: 1.0
  JPY: 0.01

# References only - no margin data here
instruments:
  CME.MNQ:
    margin_profile_id: "CME_MICRO_INDEX_V1"
  TWF.MXF:
    margin_profile_id: "TAIFEX_INDEX_V1"
  CFE.VX:
    margin_profile_id: "CME_INDEX_V1"
  CME.CL:
    margin_profile_id: "CME_ENERGY_V1"
  CME.ES:
    margin_profile_id: "CME_INDEX_V1"
  CME.6J:
    margin_profile_id: "CME_FX_V1"
  CME.MGC:
    margin_profile_id: "CME_METALS_V1"
  OSE.NK225M:
    margin_profile_id: "OSE_INDEX_V1"