end_date: null
instrument_ids:
- CME.MNQ
- TWF.MXF
policy_sha256: 0fe1ad3299b32e812887738cdb9a82d45abfe79b594e40cc366a781a2116487d
seasons:
- 2026Q1
spec_sha256: e02e5b3ab43357d7bfe7c6732e76efdbd1a287b125cb2e32c62b8f0a4ed4fe13
start_date: null
strategy_ids:
- sma_cross
- mean_revert_zscore
version: PORTFOLIO_SPEC_V1
