version: "1.0"
instruments:
  - id: "CME.MNQ"
    display_name: "E-mini Nasdaq-100"
    type: "future"
    default_profile: "CME_MNQ_TPE_v1"
    currency: "USD"
    default_timeframe: 60
    exchange: "CME"
    multiplier: 2.0
    tick_size: 0.25
    tick_value: 0.50
    timezone: "America/Chicago"
    trade_date_roll_time_local: "17:00"
  - id: "TWF.MXF"
    display_name: "Taiwan Futures Exchange Mini-TAIEX"
    type: "future"
    default_profile: "TWF_MXF_TPE_v1"
    currency: "TWD"
    default_timeframe: 60
    exchange: "TAIFEX"
    multiplier: 50.0
    tick_size: 1.0
    tick_value: 50.0
    timezone: "Asia/Taipei"
    trade_date_roll_time_local: "15:00"
default: "CME.MNQ"