version: "1.0"
margin_profiles:
  CME_INDEX_V1:
    initial_margin_per_contract: 10000.0
    maintenance_margin_per_contract: 9000.0
    margin_basis: exchange_maintenance

  CME_MICRO_INDEX_V1:
    initial_margin_per_contract: 4000.0
    maintenance_margin_per_contract: 3500.0
    margin_basis: exchange_maintenance

  CME_ENERGY_V1:
    initial_margin_per_contract: 5000.0
    maintenance_margin_per_contract: 4500.0
    margin_basis: exchange_maintenance
  
  CME_METALS_V1:
    initial_margin_per_contract: 1500.0
    maintenance_margin_per_contract: 1300.0
    margin_basis: exchange_maintenance
    
  CME_FX_V1:
    initial_margin_per_contract: 2000.0
    maintenance_margin_per_contract: 1800.0
    margin_basis: exchange_maintenance
    
  TAIFEX_INDEX_V1:
    initial_margin_per_contract: 88000.0
    maintenance_margin_per_contract: 80000.0
    margin_basis: conservative_over_exchange
    
  OSE_INDEX_V1:
    initial_margin_per_contract: 20000.0
    maintenance_margin_per_contract: 18000.0
    margin_basis: exchange_maintenance

instrument_margins:
  CME.MNQ: "CME_MICRO_INDEX_V1"
  TWF.MXF: "TAIFEX_INDEX_V1"
  CFE.VX: "CME_INDEX_V1"
  CME.CL: "CME_ENERGY_V1"
  CME.ES: "CME_INDEX_V1"
  CME.6J: "CME_FX_V1"
  CME.MGC: "CME_METALS_V1"
  OSE.NK225M: "OSE_INDEX_V1"